spring.application.name=client

server.port=4040
server.address=127.0.0.1

tunnelflow.server.websocket-url=wss://server.tunnelflow.rajeshbandi.site/ws

spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.boot=WARN
logging.level.org.tunnelflow=WARN