spring.application.name=client
server.port=4040
server.address=127.0.0.1
tunnelflow.server.websocket-url=wss://tunnelflow-production.up.railway.app/ws


logging.level.root=WARN
logging.level.org.springframework=ERROR
logging.level.org.tunnelflow=INFO